// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQTu2cy-lK2YPmWr1-zA76Xc880vh8YUk',
    appId: '1:913292900783:web:1b95e5bb704b825521175a',
    messagingSenderId: '913292900783',
    projectId: 'peria-58782',
    authDomain: 'peria-58782.firebaseapp.com',
    storageBucket: 'peria-58782.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPoleqwsEdvRAsJLNcMSG36dRjBVanlO8',
    appId: '1:913292900783:android:34430b0b3fa36c2821175a',
    messagingSenderId: '913292900783',
    projectId: 'peria-58782',
    storageBucket: 'peria-58782.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_cWM6ZrPLKzIrHDvyJ-YORukfqLf3Au4',
    appId: '1:913292900783:ios:96fc971e3046fc1421175a',
    messagingSenderId: '913292900783',
    projectId: 'peria-58782',
    storageBucket: 'peria-58782.firebasestorage.app',
    iosBundleId: 'com.example.peria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_cWM6ZrPLKzIrHDvyJ-YORukfqLf3Au4',
    appId: '1:913292900783:ios:96fc971e3046fc1421175a',
    messagingSenderId: '913292900783',
    projectId: 'peria-58782',
    storageBucket: 'peria-58782.firebasestorage.app',
    iosBundleId: 'com.example.peria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQTu2cy-lK2YPmWr1-zA76Xc880vh8YUk',
    appId: '1:913292900783:web:84901c72b6ea43fc21175a',
    messagingSenderId: '913292900783',
    projectId: 'peria-58782',
    authDomain: 'peria-58782.firebaseapp.com',
    storageBucket: 'peria-58782.firebasestorage.app',
  );
}
